### ISSUE TITLE
demo is not running when something is error.

### ISSUE THREAD

**Issue by H-TWINKLE** [MikeLINGxZ/http2tcp#6]
Thank you provide this good tool, i use it to proxy mysql and pg by this tool.
when i use it ,it is not worked.
this is error msg on server : 

![图片](https://github.com/user-attachments/assets/b3dbbef1-fd67-4b77-8208-3d747c61e802)
this is server config file:
```yaml
Host: 0.0.0.0
Port: 7889
Path: /proxy
Auth: 123456
```
this is error msg on client:
![图片](https://github.com/user-attachments/assets/d2f34b1e-1ae4-415e-b408-5142d77700e3)
```yaml
WebsocketServer: ws://192.168.2.7:7889/proxy
Auth: 123456
Targets:
  - LocalHost: 192.168.2.7
    LocalPort: 25001
    RemoteHost: 192.168.2.7
    RemotePort: 3307
  - LocalHost: 192.168.2.7
    LocalPort: 25002
    RemoteHost: 192.168.2.7
    RemotePort: 5433
```

![图片](https://github.com/user-attachments/assets/b47d1941-35f6-4038-aa2d-daab166d561a)

how can i solve this problem ?
